[package]
name = "elfvars"
version = "0.1.0"
authors = ["Grissiom <chaos.proton@gmail.com>"]

[dependencies]
xmas-elf = "0.3"
gimli = "0.11.0"
getopts = "0.2"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
log = "0.3.6"
env_logger = "0.4.0"
